### ISSUE TITLE
SfFatUtil.h doesn't exist anymore

### ISSUE THREAD

**Issue by Patronics** [sparkfun/MP3_Player_Shield#6]
When I'm trying to compile the code provided in the firmware directory, I get the error that it can't find "SdFatUtil.h", which according to [this discussion](https://forum.arduino.cc/index.php?topic=514087.0) is no longer used in modern versions of SdFat.

**Comment by MaurinElectroTextile** [comment]
Is this an update ? https://github.com/troisiemetype/SFEMP3Shield

**Comment by nseidle** [comment]
Examples have been updated. Far more simple now.
